# Generated by Django 5.0 on 2025-03-02 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('I', 'Inconnu')], default='I', max_length=1)),
                ('password', models.CharField(max_length=250)),
                ('profession_domaine', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('profile', models.ImageField(default='users/profiles/default.png', upload_to='users/profiles')),
                ('code_id', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
